Task02
cyberfined/testguru pull request #4
Opened 2021-01-15 12:23 UTC by cyberfined

Complete task02

2021-01-15 13:41 UTC, VidgarVii requested changes

2021-01-15 13:41 UTC, VidgarVii commented on app/models/answer.rb
> +end
ассоциации в этом задании не нужны. Пока учимся работать с БД
и всё-ровно не верно указаны

2021-01-15 13:41 UTC, VidgarVii commented on db/migrate/20210115113904_create_users.rb
> +end
у тебя в этом ПР 5 моделей. Значит должно быть 5 миграций. При объявлении поля надо сразу указывать все доп опции без дополнительных вызовов методов

2021-01-15 14:00 UTC, cyberfined commented on db/migrate/20210115113904_create_users.rb
> +end
Это строчка автоматически сгенерировалась при выполнении команды `rails g model users login:string{30}:uniq password:digest`

2021-01-15 14:02 UTC, cyberfined commented on app/models/answer.rb
> +end
Сейчас уберу. Они были автоматически сгенерированы из-за того, что я указал тип reference для полей user и question

2021-01-15 17:29 UTC, VidgarVii requested changes

2021-01-15 17:29 UTC, VidgarVii commented on db/migrate/20210115114045_create_tests.rb
> +      t.integer :creator_id, null: false
отношения м/у таблицами объявляются с помощью метода references
```
t.references :category, null: false, foreign_key: true
```

с автором теса по сложнее. Ищи ответ в оф. документации

2021-01-15 17:29 UTC, VidgarVii commented on db/migrate/20210115114355_create_answers.rb
> +      t.boolean :is_correct, null: false, default: false
приставку is не нужна. Так как в руби методы предикаты имеют знак '?'

2021-01-15 17:29 UTC, VidgarVii commented on db/migrate/20210115114355_create_answers.rb
> +      t.integer :user_id, null: false
а хачем тут user_id?

2021-01-15 17:34 UTC, cyberfined commented on db/migrate/20210115114045_create_tests.rb
> +      t.integer :creator_id, null: false
Я не так понял замечание насчёт ассоциаций. Я думал оно значило полностью исключить связи, поэтому я и заменил references на integer

2021-01-15 17:38 UTC, cyberfined commented on db/migrate/20210115114355_create_answers.rb
> +      t.boolean :is_correct, null: false, default: false
is_correct здесь - имя столбца в таблице

2021-01-15 17:45 UTC, cyberfined commented on db/migrate/20210115114355_create_answers.rb
> +      t.integer :user_id, null: false
Чтобы знать, какой пользователь отправил ответ. Если тесты будут с заготовленными вариантами ответов, можно убрать из данной таблицы user_id и добавить отдельную таблицу, связывающую пользователей и ответы.

2021-01-18 07:20 UTC, VidgarVii approved these changes

2021-01-18 10:20 UTC, merged