Task03
cyberfined/testguru pull request #5
Opened 2021-01-18 13:45 UTC by cyberfined

Complete task03

2021-01-18 15:47 UTC, VidgarVii requested changes

2021-01-18 15:47 UTC, VidgarVii commented on app/models/test.rb
> +  end
всё нужно решить 1 запросом. Через объединение таблиц. Когда надо получить какие-то данные из БД, то такие задачи решаются 100% с помощью SQL запросов используя обертку ОРМ.

2021-01-18 15:47 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where(id: questions.map(&:test_id), level: level)
аналогично с комментарием выше.
используй joins

2021-01-18 15:47 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :answers, through: :user_answer_mappings
как ответы связаны с пользователем? Пользователи проходят тесты, а не ответы. Задача состоит найти пройденные тесты. Ты даже в названии метода это указал.

2021-01-18 15:47 UTC, VidgarVii commented on db/migrate/20210115114045_create_tests.rb
> +      t.references :category, null: false, foreign_key: { on_delete: :cascade }
foreign_key: true!
скорей всего ты не правильно удаляешь данные

2021-01-18 15:47 UTC, VidgarVii commented on db/seeds.rb
> +categories = Category.create([{ title: 'math' }, { title: 'programming' }])
используй бэнг методы create!
Если какой-то ресурс не запишется в БД то ты увидишь ошибку. А .create просто вернут объект и ты не узнаешь, что что-то упало

2021-01-19 10:56 UTC, cyberfined commented on db/migrate/20210115114045_create_tests.rb
> +      t.references :category, null: false, foreign_key: { on_delete: :cascade }
Пока что я их не удаляю. Просто обычно для внешних ключей я ставлю ON DELETE CASCADE, чтобы при удалении данных из внешней таблицы, все строки, ссылающиеся на эти данные также удалялись.

2021-01-19 11:02 UTC, cyberfined commented on app/models/user.rb
> +  has_many :answers, through: :user_answer_mappings
Таблица answers содержит варианты ответа для каждого вопроса. Когда пользователь выбирает один из вариантов, в таблицу user_answer_mappings заносится запись с ссылкой на пользователя и ссылкой на ответ.

2021-01-19 11:59 UTC, VidgarVii requested changes

2021-01-19 11:59 UTC, VidgarVii commented on app/models/test.rb
> +  end
сокращение убивает читаемость кода
AS очень редкий кейс когда он действительно нужен. В основном при жутко нормализованной или плохо с проектированная БД.

2021-01-19 11:59 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :answers, through: :user_answer_mappings
пока у тебя ни чего не заносится +)
Такая сложность не понадобиться. В задаче не стояла подобная логика

2021-01-19 11:59 UTC, VidgarVii commented on app/models/answer.rb
> +  has_many :users, through: :user_answer_mappings
ассоциации не нужны в этом ДЗ. Будешь их делать после следующего урока. И сразу правильно

2021-01-19 11:59 UTC, VidgarVii commented on db/migrate/20210115114045_create_tests.rb
> +      t.references :category, null: false, foreign_key: { on_delete: :cascade }
хорошо. но обычно это решают методами АР. 
1 данную логику решает метод destroy. Посмотри отличие методов destroy/delete
2 так же это мы будем прописывать при объявлении ассоциаций в моделях

пусть БД только хранит данные и следит, что бы сохранялась целостность. Чем она проще и понятней тем лучше.

2021-01-19 11:59 UTC, VidgarVii commented on app/models/user.rb
> +  end
название метода хорошее. Реализация ужасная. 
Тебе нужна всего одна промежуточная таблица результатов. между юзером и тестом. Не надо ни чего в ответы писать. Не их эта задача. Ответы ни какого отношения с юзерами не имеют. Они сам по себе. И знают только к какому вопросу принадлежат

2021-01-19 12:04 UTC, VidgarVii commented on db/seeds.rb
> +                          { user_id: users.second.id, answer_id: answers[5].id }])
еще хорошо было бы проверку добавить, на наличие данных в таблице, чтобы при повторном запуске сидов они данные не продублировали. Сиды не должны портить базу.

2021-01-20 08:15 UTC, VidgarVii requested changes

2021-01-20 08:15 UTC, VidgarVii commented on app/models/test.rb
> +      where('categories.title = ?', category).
where(categories: { title: category })

2021-01-20 08:15 UTC, VidgarVii commented on app/models/user.rb
> +      where('results.user_id = ? AND tests.level = ?', id, level).
тут так же лучше использовть хеш в методе where

2021-01-20 13:28 UTC, merged