Task04
cyberfined/testguru pull request #6
Opened 2021-01-20 14:59 UTC by cyberfined

Complete task04

2021-01-20 16:40 UTC, VidgarVii requested changes

2021-01-20 16:40 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:

```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```

и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2021-01-20 16:40 UTC, VidgarVii commented on app/models/test.rb
>        where(categories: { title: category }).
старые методы следует отрефактить используя хеши и ассоциации

2021-01-21 13:11 UTC, VidgarVii requested changes

2021-01-21 13:11 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers, dependent: :delete_all
dependent: :destroy

delete не учитывает каскадное удаление и может привести к ошибке

2021-01-21 13:11 UTC, VidgarVii commented on db/migrate/20210119130856_create_results.rb
> +      t.index [:user_id, :test_id], unique: true
зачем тут уникальный индекс ? Как пользователь сможет пройти тест еще раз?

2021-01-21 14:30 UTC, cyberfined commented on db/migrate/20210119130856_create_results.rb
> +      t.index [:user_id, :test_id], unique: true
Я думал, что такой опции не предусмотрено

2021-01-21 14:31 UTC, cyberfined commented on app/models/question.rb
> +  has_many :answers, dependent: :delete_all
Я знаю, просто в ответах нет никаких зависимостей, их можно свободно удалять. С другой стороны, если в будущем придётся изменить модель ответов, этот факт может стать ложным.

2021-01-22 06:31 UTC, VidgarVii requested changes

2021-01-22 06:31 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :results, dependent: :delete_all
dependent: :delete_all не вызовет колбек dependent у модели Result.
Сейчас такого кейса конечно нет. К Result не имеет связи has_* Но если появится, то данную строчку исправить забудешь 100%
 Лучше по умолчанию ставить destroy

2021-01-22 06:31 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :results, dependent: :delete_all
М/у belongs_to и has_many оставляют пустую строку

2021-01-22 06:31 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins(:category).where(categories: { title: category }).pluck(:title)
Test тут лишний

2021-01-22 06:31 UTC, VidgarVii commented on db/seeds.rb
>  if Test.first.nil?
.exists?

2021-01-22 06:31 UTC, VidgarVii commented on db/seeds.rb
>  if Result.first.nil?
нет смысла проверять все таблицы. Да и это приведет к багу. Надо смотреть только в 1 таблицу. Тут надо учитывать иерархию часть/целое

2021-01-22 13:43 UTC, VidgarVii approved these changes

2021-01-22 13:49 UTC, merged