Task05
cyberfined/testguru pull request #7
Opened 2021-01-24 15:49 UTC by cyberfined

Complete task05

2021-01-24 17:15 UTC, VidgarVii requested changes

2021-01-24 17:15 UTC, VidgarVii commented on app/models/answer.rb
> +  validates :statement, presence: true
валидации принято писать выше скоупов
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods

2021-01-24 17:15 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(:title) }
default_scope в самом верху. Так как он часто вызывает кучу проблем

2021-01-24 17:15 UTC, VidgarVii commented on app/models/question.rb
> +  validate :validate_num_answers
задача валидировать ответы. Значит валидация должна находиться в модели Ответ

2021-01-24 17:15 UTC, VidgarVii commented on app/models/test.rb
> +  scope :hard_tests, -> { where(level: 5..Float::INFINITY) }
в методах часто дублируешь название объекта. Это не очень хорошая практика. Когда ты обращаешься к человеку, ты ведь не называешь его имя 2 раза.

2021-01-24 20:44 UTC, cyberfined commented on app/models/question.rb
> +  validate :validate_num_answers
Задача же проверить, что вопрос содержит от 1 до 4 ответов. Разве это не валидация вопросов?

2021-01-25 11:52 UTC, VidgarVii requested changes

2021-01-25 11:52 UTC, VidgarVii commented on app/models/question.rb
> +  validate :validate_num_answers
надо указать в каких ситуациях мы должны использовать данную валидацию. Иначе кол-во ответов в вопросе, будет проверяться даже при редактировании ответа

2021-01-25 11:52 UTC, VidgarVii commented on app/models/question.rb
> +    if answers.length < 1 || answers.length > 4
`length` вернет объекты в памяти, тут тоже простор для путанницы...
нужно соображать - а входит в этот список создаваемый объект или нет?...
а создаваемый объект входит в список объектов в памяти, и значит 4-ый вопрос твоя валидация уже не даст создать если использовать `count`, то получаем количество объекто в базе, без двусмысленностей

по поводу методов подсчета объектов `count`, `size`, `length` - посмотри для самообразования [вот этот вопрос на СО](https://stackoverflow.com/questions/6083219/activerecord-size-vs-count) и конечно же ответы к нему
1-ый и 2-ой ответы довольно лаконично и понятно объясняют что делают методы


можно и без OR

2021-01-26 11:09 UTC, cyberfined commented on app/models/question.rb
> +  validate :validate_num_answers
Странно, но валидация не происходит при исполнении данного кода:
`q = Question.find(1)                                                                                
a = q.answers[0]                                                                                    
a.update!(correct: false)`

2021-01-27 16:27 UTC, VidgarVii requested changes

2021-01-27 16:27 UTC, VidgarVii commented on app/models/question.rb
> +  validate :validate_num_answers
валидация в модели Вопрос не будет препятствовать созданию новых ответов в количестве больше 4, потому что она не будет вызываться при добавлении новых ответов к вопросу

валидации в классе Вопрос вызываются при создании или изменении объектов класса Вопрос
при создании объектов класса Ответ валидации в классе Вопрос не вызываются

видимо ты не проверял работу этой валидации

2021-01-28 17:22 UTC, VidgarVii commented on app/models/answer.rb
> +    if question.answers.count > MAXIMUM_ANSWERS-1
без вычитаний будет лучше смотреться . используй <=

2021-01-28 17:26 UTC, merged