Task06
cyberfined/testguru pull request #8
Opened 2021-01-29 00:52 UTC by cyberfined

Complete task06

2021-01-29 17:31 UTC, VidgarVii requested changes

2021-01-29 17:31 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
1 безопасней использовать strong params
2 Если вопрос на создастся (из-за валидации например) клиент этого не узнает. Надо добавить проверку записи ресурса в БД и далее действовать из ходя из результат
```
if @question.save
  redirect_to ...
else
  render :new
end
```
3 не надо передавать тест в параметрах. Тут могут быть проблемы. Используй интерфейс запроса has_many
test.questions.build()

2021-01-30 15:35 UTC, VidgarVii requested changes

2021-01-30 15:35 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to "/tests/#{@test.id}/questions"
по rails way надо использовать урл хелперы. либо объект
redirect_to @question

2021-01-30 15:35 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to :new_test_question
если будет ошибка, то не надо переключать страницу. Надо просто отрендерить ту же форму
render :new

2021-01-30 16:12 UTC, cyberfined commented on app/controllers/questions_controller.rb
> +      redirect_to :new_test_question
Если так сделать, то URL будет /tests/:test_id/questions, а не /tests/:test_id/questions/new

2021-01-31 18:30 UTC, VidgarVii requested changes

2021-01-31 18:30 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to :new_test_question
http://rusrails.ru/action-controller-overview#parametry

2021-01-31 18:30 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render(plain: exception.message)
согласно dsl rails для render не ставят скобки

2021-02-01 16:36 UTC, merged