Task07
cyberfined/testguru pull request #9
Opened 2021-02-03 20:45 UTC by cyberfined

2021-02-04 06:24 UTC, VidgarVii requested changes

2021-02-04 06:24 UTC, VidgarVii commented on app/assets/javascript/application.js
> +}
вот это всё не нужно и уже имеется из под коробки
http://rusrails.ru/ruby-on-rails-security-guide#csrf-countermeasures

2021-02-04 06:24 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    end
согласно ДЗ этот экшен не нужен

2021-02-04 06:24 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>        redirect_to :test_questions
на какой тест будет редирект? надо указать явно

2021-02-04 06:24 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
надо реализовать

2021-02-04 06:24 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    end
нужен шаблон

2021-02-04 06:24 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +    link_to(repo, "https://github.com/#{author}/#{repo}")
новая вкладка/rel=nofollow

2021-02-04 06:24 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +    Date.today.year
надо учитывать временную зону

2021-02-04 06:24 UTC, VidgarVii commented on app/helpers/question_helper.rb
> +  end
в метод достаточно передать объект вопроса, и взять у него все нужные и актуальные данные

2021-02-04 06:24 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<%= form_with model: model do |form| %>
https://apidock.com/rails/ActionView/Helpers/FormHelper/form_with

2021-02-04 06:24 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +  <% for question in @test.questions %>
используй render collection

2021-02-04 06:24 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +  <% @tests.each do |test| %>
используй render collection

2021-02-04 08:57 UTC, cyberfined commented on app/controllers/questions_controller.rb
>    end
Он нужен для отображения всех вопросов теста

2021-02-04 10:24 UTC, cyberfined commented on app/assets/javascript/application.js
> +}
У меня rails ругался на отсутствие application.js, поэтому я написал свой. Это связано с тем, что я создал приложение без webpack, т.к. с его установкой были некоторые проблемы

2021-02-04 10:26 UTC, cyberfined commented on app/views/questions/_form.html.erb
> +<%= form_with model: model do |form| %>
Я сделал model локальной переменной, т.к. для создания вопроса нужно передать [test, question], а для редактирования только question.

2021-02-04 13:49 UTC, VidgarVii requested changes

2021-02-04 13:49 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<%= form_with model: model do |form| %>
1 нужна опция чтобы форма отправляла методом GET
2 шапку формы можно объявлять в макетах new/edit. А в партиал положить только поля. 
3 названия партиала, не соответствует коду

2021-02-04 13:49 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +</table>
а этот тег какую таблицу закрывает?

2021-02-04 13:49 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +  end
Time.current.year

2021-02-05 06:15 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    end
прочти еще раз задание. и делай согласно ДЗ

2021-02-05 06:18 UTC, cyberfined commented on app/controllers/questions_controller.rb
>    end
Я неправильно понял первый пункт. Сейчас переделаю

2021-02-05 06:19 UTC, VidgarVii requested changes

2021-02-05 06:19 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<%= form_with model: [@test, @question] do |form| %>
все формы имеют метод запроса post. надо поставить на GET

2021-02-05 06:19 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +end
экшены не раелизованы.
**Список вопросов теста должен выводиться на той же странице, что и сам тест**
нужна страница теста

2021-02-05 06:23 UTC, cyberfined commented on app/views/questions/new.html.erb
> +<%= form_with model: [@test, @question] do |form| %>
Почему? Они же нужны для отправки запроса на создание и обновление вопроса, а не его получение

2021-02-07 12:25 UTC, closed without merging